framework:
    default_locale: eo
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks: ['fr', 'en']
#            fr: ['en']
#            eo: ['en']
#            br: ['fr', 'en']
#            galo: ['fr', 'en']

#        providers:
#            crowdin:
#                dsn: '%env(CROWDIN_DSN)%'
#            loco:
#                dsn: '%env(LOCO_DSN)%'
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
